[package]
name = "coreaudio-hl"
version = "0.1.0"
edition = "2021"

[dependencies]
coreaudio-sys = { version = "0.2.15", default-features = false, features = [
    "core_audio",
] }
thiserror = "1.0.61"
